import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:shared_preferences/shared_preferences.dart';

import '../core/config.dart';
import '../domain/models.dart';

/// The UI only talks to this. Swap MockRepository for ApiRepository with --dart-define=USE_MOCK=false.
abstract class IdeaRepository {
  Future<Bundle> loadBundle();
}

/// Fixture data bundled with the app (generated by backend/scripts/generate_sample.py).
class MockRepository implements IdeaRepository {
  @override
  Future<Bundle> loadBundle() async {
    final raw = await rootBundle.loadString('assets/mock/data.json');
    return Bundle.fromJson(jsonDecode(raw) as Map<String, dynamic>);
  }
}

/// Live backend, with an on-device cache so saved and recent items still open without a connection.
class ApiRepository implements IdeaRepository {
  ApiRepository({Dio? dio}) : _dio = dio ?? Dio(BaseOptions(baseUrl: AppConfig.apiBaseUrl, connectTimeout: const Duration(seconds: 8), receiveTimeout: const Duration(seconds: 15)));

  final Dio _dio;
  static const _cacheKey = 'bundle_cache_v1';

  @override
  Future<Bundle> loadBundle() async {
    final prefs = await SharedPreferences.getInstance();
    try {
      final res = await _dio.get<Map<String, dynamic>>('/v1/bundle');
      final data = res.data!;
      await prefs.setString(_cacheKey, jsonEncode(data));
      return Bundle.fromJson(data);
    } on DioException {
      final cached = prefs.getString(_cacheKey);
      if (cached == null) rethrow;
      return Bundle.fromJson(jsonDecode(cached) as Map<String, dynamic>).asOffline();
    }
  }
}
